# Generated by Django 5.1.1 on 2024-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisasterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelter_id", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=100)),
                ("office_phone", models.CharField(max_length=50)),
                ("is_storage_point", models.BooleanField()),
                ("community", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("service_community", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("max_capacity", models.IntegerField()),
                ("indoor_capacity", models.IntegerField()),
                ("outdoor_capacity", models.IntegerField()),
                ("indoor_area", models.FloatField()),
                ("outdoor_area", models.FloatField()),
                (
                    "disaster_support_types",
                    models.ManyToManyField(to="shelters.disastertype"),
                ),
            ],
        ),
    ]
